# Generated by Django 3.2.12 on 2022-02-19 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='catgerory',
            fields=[
                ('catgerory_id', models.AutoField(primary_key=True, serialize=False)),
                ('catgerory_name', models.CharField(max_length=200, verbose_name='uname')),
                ('catgerory_address', models.CharField(max_length=200, verbose_name='address')),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('logid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, verbose_name='username')),
                ('password', models.CharField(max_length=100, verbose_name='password')),
                ('role', models.CharField(max_length=10, verbose_name='role')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('User_id', models.AutoField(primary_key=True, serialize=False)),
                ('User_name', models.CharField(max_length=200, verbose_name='uname')),
                ('User_address', models.CharField(max_length=200, verbose_name='address')),
                ('User_email', models.CharField(max_length=100, verbose_name='email')),
                ('User_phone', models.CharField(max_length=100, verbose_name='phone')),
                ('User_alt_No', models.CharField(max_length=200, verbose_name='altno')),
                ('User_status', models.CharField(max_length=200, verbose_name='status')),
                ('Log_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='health.login')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('Provide_id', models.AutoField(primary_key=True, serialize=False)),
                ('Provide_name', models.CharField(max_length=100, verbose_name='Name')),
                ('Provide_address', models.CharField(max_length=500, verbose_name='Staff_address')),
                ('Provide_email', models.EmailField(max_length=200, verbose_name='Staff_email')),
                ('Provide_phone', models.CharField(max_length=100, verbose_name='Staff_phone')),
                ('Provide_qualification', models.CharField(max_length=200, verbose_name='Staff_qualification')),
                ('Provide_designation', models.CharField(max_length=100, verbose_name='Staff_designation')),
                ('Provide_experience', models.CharField(max_length=100, verbose_name='Staff_experience')),
                ('Provide_photo', models.FileField(max_length=1000, upload_to='images/', verbose_name='Staff_photo')),
                ('Provide_status', models.CharField(default='', max_length=50, verbose_name='Staff_status')),
                ('Provide_logid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='health.login')),
                ('catgerory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='health.catgerory')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('Feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('Feedback_subject', models.CharField(max_length=100, verbose_name='subject')),
                ('Feedback_message', models.CharField(max_length=500, verbose_name='message')),
                ('Feedback_date', models.CharField(max_length=100, verbose_name='date')),
                ('Feedback_reply', models.CharField(max_length=500, verbose_name='replay')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='health.user')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('Complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('Complaint_subject', models.CharField(max_length=100, verbose_name='subject')),
                ('Complaint_message', models.CharField(max_length=500, verbose_name='message')),
                ('Complaint_date', models.CharField(max_length=100, verbose_name='date')),
                ('Complaint_reply', models.CharField(max_length=500, verbose_name='replay')),
                ('Provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='health.provider')),
            ],
        ),
    ]
