# Generated by Django 3.2.12 on 2022-02-21 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='Provide_designation',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='Provide_experience',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='Provide_photo',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='Provide_qualification',
        ),
        migrations.RemoveField(
            model_name='user',
            name='User_alt_No',
        ),
        migrations.AddField(
            model_name='provider',
            name='Provide_district',
            field=models.CharField(default='', max_length=100, verbose_name='Staff_district'),
        ),
        migrations.AddField(
            model_name='provider',
            name='Provide_location',
            field=models.CharField(default='', max_length=200, verbose_name='Staff_location'),
        ),
        migrations.AddField(
            model_name='provider',
            name='Provide_tharif',
            field=models.CharField(default='', max_length=100, verbose_name='Staff_tharif'),
        ),
        migrations.AddField(
            model_name='user',
            name='User_district',
            field=models.CharField(default='', max_length=200, verbose_name='district'),
        ),
        migrations.AddField(
            model_name='user',
            name='User_location',
            field=models.CharField(default='', max_length=200, verbose_name='location'),
        ),
        migrations.CreateModel(
            name='servicerequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_type', models.CharField(max_length=100, verbose_name='service_type')),
                ('service_details', models.CharField(max_length=1000, verbose_name='service_details')),
                ('reg_date', models.EmailField(max_length=200, verbose_name='reg_date')),
                ('request_date', models.CharField(max_length=100, verbose_name='request_date')),
                ('request_rating', models.CharField(max_length=200, verbose_name='request_rating')),
                ('request_status', models.CharField(default='', max_length=50, verbose_name='request_status')),
                ('Provide_logid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='health.login')),
                ('catgerory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='health.catgerory')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='health.user')),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('Pay_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.CharField(max_length=100, verbose_name='amount')),
                ('pay_status', models.CharField(max_length=100, verbose_name='pay_status')),
                ('servicerequest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='health.servicerequest')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='health.user')),
            ],
        ),
    ]
