# Generated by Django 3.2.12 on 2022-02-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_auto_20220221_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='Provide_doc',
            field=models.FileField(default=1, max_length=1000, upload_to='images/', verbose_name='Provide_doc'),
            preserve_default=False,
        ),
    ]
